-- WoW Chat Helper: built-in offline glossary (WoW: Forever, 2004-era Azeroth, level 60).
-- Chinese is Traditional (zh-TW, Taiwan gamer wording).
-- cat: lfg, raid, loot, role, class, combat, trade, social, zone, misc.
-- phrases: whole-message table for the offline short-circuit. Keys are normalized:
-- lowercase, trimmed, single spaces, no trailing punctuation.
WCH_Glossary = {
  terms = {
    -- lfg
    { term="LFG", expansion="Looking For Group", zh="找隊伍", cat="lfg" },
    { term="LFM", expansion="Looking For More", zh="徵人", cat="lfg" },
    { term="LF1M", expansion="Looking For 1 More", zh="還缺一人", cat="lfg" },
    { term="LF2M", expansion="Looking For 2 More", zh="還缺兩人", cat="lfg" },
    { term="LF3M", expansion="Looking For 3 More", zh="還缺三人", cat="lfg" },
    { term="LF4M", expansion="Looking For 4 More", zh="還缺四人", cat="lfg" },
    { term="LFW", expansion="Looking For Work", zh="找人帶或找工作", cat="lfg" },
    { term="LF", expansion="Looking For", zh="尋找", cat="lfg" },
    { term="inv", expansion="invite", zh="邀請", cat="lfg" },
    { term="invite", expansion="invite to group", zh="邀請入隊", cat="lfg" },
    { term="pst", expansion="please send tell", zh="請密我", cat="lfg" },
    { term="pm", expansion="private message", zh="私訊", cat="lfg" },
    { term="tell", expansion="whisper", zh="密語", cat="lfg" },
    { term="whisper", expansion="private chat message", zh="密語", cat="lfg" },
    { term="/w", expansion="whisper command", zh="密語指令", cat="lfg" },
    { term="group", expansion="party of up to 5 players", zh="隊伍", cat="lfg" },
    { term="party", expansion="group of up to 5 players", zh="五人小隊", cat="lfg" },
    { term="raid", expansion="large group up to 40", zh="團隊", cat="lfg" },
    { term="pug", expansion="pick-up group", zh="路人隊", cat="lfg" },
    { term="guild run", expansion="dungeon run with guildies", zh="公會副本", cat="lfg" },
    { term="full", expansion="group is full", zh="滿了", cat="lfg" },
    { term="need", expansion="we need more players", zh="還缺", cat="lfg" },
    { term="spot", expansion="open slot in group", zh="位置", cat="lfg" },
    { term="spots left", expansion="open slots remaining", zh="還剩位置", cat="lfg" },
    { term="last spot", expansion="only one slot left", zh="最後一個位置", cat="lfg" },
    { term="summ", expansion="summon", zh="召喚", cat="lfg" },
    { term="summon", expansion="warlock summon to instance", zh="召喚進副本", cat="lfg" },
    { term="port", expansion="mage teleport or portal", zh="傳送", cat="lfg" },
    { term="portal", expansion="mage portal", zh="傳送門", cat="lfg" },
    { term="meet at", expansion="meet at the location", zh="在那邊集合", cat="lfg" },
    { term="stone", expansion="meeting stone", zh="集合石", cat="lfg" },
    { term="meeting stone", expansion="summoning stone at dungeon entrance", zh="副本入口集合石", cat="lfg" },
    { term="ready check", expansion="ready check", zh="確認就緒", cat="lfg" },
    { term="rdy", expansion="ready", zh="準備好了", cat="lfg" },
    { term="ready", expansion="ready to go", zh="準備好了", cat="lfg" },
    { term="all in", expansion="everyone is here", zh="人都到齊", cat="lfg" },
    { term="inc", expansion="incoming", zh="有怪來了", cat="lfg" },
    { term="gather", expansion="gather the group", zh="集合", cat="lfg" },
    { term="dungeon", expansion="five-man instance", zh="五人副本", cat="lfg" },
    { term="instance", expansion="dungeon or raid", zh="副本", cat="lfg" },
    { term="inst", expansion="instance", zh="副本", cat="lfg" },
    { term="HC", expansion="Heroic", zh="英雄難度", cat="lfg" },
    { term="heroic", expansion="harder dungeon difficulty", zh="英雄難度", cat="lfg" },
    { term="normal", expansion="normal difficulty", zh="普通難度", cat="lfg" },
    { term="reset", expansion="instance reset", zh="重置副本", cat="lfg" },
    { term="lockout", expansion="saved instance timer", zh="副本進度鎖定", cat="lfg" },
    { term="saved", expansion="locked to a raid", zh="已有進度", cat="lfg" },
    { term="clear", expansion="finish the whole instance", zh="全清", cat="lfg" },
    { term="full clear", expansion="kill every boss", zh="全部打完", cat="lfg" },
    { term="run", expansion="a dungeon or raid run", zh="跑一趟副本", cat="lfg" },
    { term="carry", expansion="higher level helps lower players", zh="帶人過", cat="lfg" },
    { term="boost", expansion="power-level service", zh="代打或帶練", cat="lfg" },
    { term="quest", expansion="mission", zh="任務", cat="lfg" },
    { term="quests", expansion="missions", zh="任務", cat="lfg" },
    { term="elite", expansion="elite quest or mob", zh="精英", cat="lfg" },
    { term="group quest", expansion="quest requiring a party", zh="組隊任務", cat="lfg" },
    { term="turn in", expansion="hand in quest", zh="交任務", cat="lfg" },
    { term="grind", expansion="kill mobs repeatedly for XP", zh="刷怪練功", cat="lfg" },
    { term="grinding", expansion="farming mobs for XP", zh="刷怪練功中", cat="lfg" },
    { term="leveling", expansion="gaining levels", zh="練等", cat="lfg" },
    { term="lvl", expansion="level", zh="等級", cat="lfg" },
    { term="level", expansion="character level", zh="等級", cat="lfg" },
    { term="60", expansion="max level", zh="滿級六十", cat="lfg" },
    { term="alt", expansion="alternate character", zh="小號", cat="lfg" },
    { term="main", expansion="main character", zh="主角色", cat="lfg" },
    { term="twink", expansion="low-level geared character", zh="裝備很好的低等角色", cat="lfg" },
    { term="rested", expansion="rested XP bonus", zh="休息經驗加成", cat="lfg" },
    { term="XP", expansion="experience points", zh="經驗值", cat="lfg" },
    { term="exp", expansion="experience", zh="經驗", cat="lfg" },
    -- zone / dungeons
    { term="DM", expansion="Dire Maul", zh="厄運之槌", cat="zone" },
    { term="DM East", expansion="Dire Maul East", zh="厄運之槌東區", cat="zone" },
    { term="DM West", expansion="Dire Maul West", zh="厄運之槌西區", cat="zone" },
    { term="DM North", expansion="Dire Maul North", zh="厄運之槌北區", cat="zone" },
    { term="VC", expansion="Deadmines (VanCleef)", zh="死亡礦坑", cat="zone" },
    { term="Deadmines", expansion="Deadmines dungeon", zh="死亡礦坑", cat="zone" },
    { term="RFC", expansion="Ragefire Chasm", zh="怒焰裂谷", cat="zone" },
    { term="WC", expansion="Wailing Caverns", zh="哀嚎洞穴", cat="zone" },
    { term="SFK", expansion="Shadowfang Keep", zh="影牙城堡", cat="zone" },
    { term="BFD", expansion="Blackfathom Deeps", zh="黑暗深淵", cat="zone" },
    { term="Stocks", expansion="The Stockade", zh="監獄", cat="zone" },
    { term="Stockade", expansion="The Stockade", zh="監獄", cat="zone" },
    { term="Gnomer", expansion="Gnomeregan", zh="諾姆瑞根", cat="zone" },
    { term="RFK", expansion="Razorfen Kraul", zh="剃刀沼澤", cat="zone" },
    { term="RFD", expansion="Razorfen Downs", zh="剃刀高地", cat="zone" },
    { term="SM", expansion="Scarlet Monastery", zh="血色修道院", cat="zone" },
    { term="SM GY", expansion="Scarlet Monastery Graveyard", zh="血色修道院墓地", cat="zone" },
    { term="SM Lib", expansion="Scarlet Monastery Library", zh="血色修道院圖書館", cat="zone" },
    { term="SM Arm", expansion="Scarlet Monastery Armory", zh="血色修道院軍械庫", cat="zone" },
    { term="SM Cath", expansion="Scarlet Monastery Cathedral", zh="血色修道院大教堂", cat="zone" },
    { term="ULD", expansion="Uldaman", zh="奧達曼", cat="zone" },
    { term="ZF", expansion="Zul'Farrak", zh="祖爾法拉克", cat="zone" },
    { term="Mara", expansion="Maraudon", zh="瑪拉頓", cat="zone" },
    { term="ST", expansion="Sunken Temple", zh="沉默神廟", cat="zone" },
    { term="BRD", expansion="Blackrock Depths", zh="黑石深淵", cat="zone" },
    { term="LBRS", expansion="Lower Blackrock Spire", zh="下黑石塔", cat="zone" },
    { term="UBRS", expansion="Upper Blackrock Spire", zh="上黑石塔", cat="zone" },
    { term="BRS", expansion="Blackrock Spire", zh="黑石塔", cat="zone" },
    { term="Strat", expansion="Stratholme", zh="斯坦索姆", cat="zone" },
    { term="Scholo", expansion="Scholomance", zh="通靈學院", cat="zone" },
    { term="MC", expansion="Molten Core", zh="熔火之心", cat="raid" },
    { term="Ony", expansion="Onyxia's Lair", zh="奧妮克希亞", cat="raid" },
    { term="Onyxia", expansion="Onyxia's Lair raid", zh="奧妮克希亞", cat="raid" },
    { term="ZG", expansion="Zul'Gurub", zh="祖爾格拉布", cat="raid" },
    { term="BWL", expansion="Blackwing Lair", zh="黑翼之巢", cat="raid" },
    { term="AQ20", expansion="Ruins of Ahn'Qiraj", zh="安其拉廢墟", cat="raid" },
    { term="AQ40", expansion="Temple of Ahn'Qiraj", zh="安其拉神廟", cat="raid" },
    { term="Naxx", expansion="Naxxramas", zh="納克薩瑪斯", cat="raid" },
    { term="Kara", expansion="Karazhan", zh="卡拉贊", cat="raid" },
    { term="Ragnaros", expansion="Molten Core final boss", zh="拉格納羅斯", cat="raid" },
    { term="Rag", expansion="Ragnaros", zh="拉格納羅斯", cat="raid" },
    { term="Geddon", expansion="Baron Geddon", zh="迦頓男爵", cat="raid" },
    { term="Domo", expansion="Majordomo Executus", zh="管理者埃克索圖斯", cat="raid" },
    { term="Magmadar", expansion="Molten Core boss", zh="瑪格曼達", cat="raid" },
    { term="Lucifron", expansion="Molten Core boss", zh="魯西弗隆", cat="raid" },
    { term="Garr", expansion="Molten Core boss", zh="加爾", cat="raid" },
    { term="Shaz", expansion="Shazzrah", zh="沙斯拉爾", cat="raid" },
    { term="Sulfuron", expansion="Sulfuron Harbinger", zh="薩弗隆先驅者", cat="raid" },
    { term="Golemagg", expansion="Molten Core boss", zh="古雷曼格", cat="raid" },
    { term="Nef", expansion="Nefarian", zh="奈法利安", cat="raid" },
    { term="Vael", expansion="Vaelastrasz", zh="維拉斯塔茲", cat="raid" },
    { term="Chromaggus", expansion="BWL boss", zh="克洛瑪古斯", cat="raid" },
    { term="Hakkar", expansion="Zul'Gurub final boss", zh="哈卡", cat="raid" },
    { term="Hakkar debuff", expansion="Corrupted Blood", zh="腐血", cat="raid" },
    { term="Cenarion", expansion="Cenarion Circle faction", zh="塞納里奧議會", cat="zone" },
    { term="Booty Bay", expansion="neutral goblin port in STV", zh="藏寶海灣", cat="zone" },
    { term="BB", expansion="Booty Bay", zh="藏寶海灣", cat="zone" },
    { term="SW", expansion="Stormwind", zh="暴風城", cat="zone" },
    { term="IF", expansion="Ironforge", zh="鐵爐堡", cat="zone" },
    { term="Darn", expansion="Darnassus", zh="達納蘇斯", cat="zone" },
    { term="Org", expansion="Orgrimmar", zh="奧格瑪", cat="zone" },
    { term="UC", expansion="Undercity", zh="幽暗城", cat="zone" },
    { term="TB", expansion="Thunder Bluff", zh="雷霆崖", cat="zone" },
    { term="STV", expansion="Stranglethorn Vale", zh="荊棘谷", cat="zone" },
    { term="EPL", expansion="Eastern Plaguelands", zh="東瘟疫之地", cat="zone" },
    { term="WPL", expansion="Western Plaguelands", zh="西瘟疫之地", cat="zone" },
    { term="Winterspring", expansion="Winterspring zone", zh="冬泉谷", cat="zone" },
    { term="Felwood", expansion="Felwood zone", zh="費伍德森林", cat="zone" },
    { term="Silithus", expansion="Silithus zone", zh="希利蘇斯", cat="zone" },
    { term="Un'Goro", expansion="Un'Goro Crater", zh="安戈洛環形山", cat="zone" },
    { term="Tanaris", expansion="Tanaris desert", zh="塔納利斯", cat="zone" },
    { term="BRM", expansion="Blackrock Mountain", zh="黑石山", cat="zone" },
    { term="Burning Steppes", expansion="zone near BRM", zh="燃燒平原", cat="zone" },
    { term="Searing Gorge", expansion="zone near BRM", zh="灼熱峽谷", cat="zone" },
    { term="Hinterlands", expansion="The Hinterlands", zh="辛特蘭", cat="zone" },
    { term="Duskwood", expansion="Duskwood zone", zh="暮色森林", cat="zone" },
    { term="Westfall", expansion="Westfall zone", zh="西部荒野", cat="zone" },
    { term="Barrens", expansion="The Barrens", zh="貧瘠之地", cat="zone" },
    { term="Crossroads", expansion="Crossroads in Barrens", zh="十字路口", cat="zone" },
    { term="Ironforge tram", expansion="Deeprun Tram", zh="礦道地鐵", cat="zone" },
    { term="tram", expansion="Deeprun Tram", zh="地鐵", cat="zone" },
    { term="FP", expansion="flight path", zh="飛行點", cat="zone" },
    { term="boat", expansion="boat ride between continents", zh="船", cat="zone" },
    { term="zep", expansion="zeppelin", zh="飛艇", cat="zone" },
    { term="zeppelin", expansion="Horde airship", zh="飛艇", cat="zone" },
    { term="HS", expansion="Hearthstone", zh="爐石", cat="zone" },
    { term="hearth", expansion="use Hearthstone", zh="用爐石回城", cat="zone" },
    { term="bind", expansion="set Hearthstone home", zh="綁定爐石", cat="zone" },
    { term="graveyard", expansion="spirit healer location", zh="墓地", cat="zone" },
    { term="GY", expansion="graveyard", zh="墓地", cat="zone" },
    { term="corpse", expansion="dead body", zh="屍體", cat="zone" },
    { term="CR", expansion="corpse run", zh="跑屍體", cat="zone" },
    { term="spirit healer", expansion="NPC that resurrects ghosts", zh="靈魂醫者", cat="zone" },
    { term="ghost", expansion="dead spirit form", zh="靈魂狀態", cat="zone" },
    -- raid / combat
    { term="MT", expansion="Main Tank", zh="主坦", cat="raid" },
    { term="OT", expansion="Off Tank", zh="副坦", cat="raid" },
    { term="boss", expansion="boss monster", zh="王", cat="raid" },
    { term="trash", expansion="regular mobs", zh="小怪", cat="raid" },
    { term="mob", expansion="monster", zh="怪物", cat="combat" },
    { term="mobs", expansion="monsters", zh="怪物們", cat="combat" },
    { term="add", expansion="extra enemy joining the fight", zh="小怪加入戰鬥", cat="raid" },
    { term="adds", expansion="extra enemies", zh="增援小怪", cat="raid" },
    { term="wipe", expansion="whole group dies", zh="滅團", cat="raid" },
    { term="wiped", expansion="whole group died", zh="團滅了", cat="raid" },
    { term="rez", expansion="resurrect", zh="復活", cat="raid" },
    { term="res", expansion="resurrect", zh="復活", cat="raid" },
    { term="ress", expansion="resurrect", zh="復活", cat="raid" },
    { term="brez", expansion="battle resurrection", zh="戰鬥復活", cat="raid" },
    { term="soulstone", expansion="warlock self-rez item", zh="靈魂石", cat="raid" },
    { term="ankh", expansion="shaman reincarnation", zh="復生", cat="raid" },
    { term="pull", expansion="start fight with a mob", zh="拉怪", cat="raid" },
    { term="pulling", expansion="pulling mobs", zh="正在拉怪", cat="raid" },
    { term="pulled", expansion="mob has been pulled", zh="已經拉怪", cat="raid" },
    { term="chain pull", expansion="pull next pack immediately", zh="連拉", cat="raid" },
    { term="aggro", expansion="monster attention", zh="仇恨", cat="raid" },
    { term="threat", expansion="aggro value", zh="仇恨值", cat="raid" },
    { term="overaggro", expansion="took aggro from tank", zh="把仇恨拉走了", cat="raid" },
    { term="LOS", expansion="line of sight", zh="躲視線", cat="raid" },
    { term="kite", expansion="run while mob chases", zh="風箏", cat="raid" },
    { term="CC", expansion="crowd control", zh="控場", cat="raid" },
    { term="sheep", expansion="mage Polymorph", zh="羊", cat="raid" },
    { term="poly", expansion="Polymorph", zh="變羊", cat="raid" },
    { term="polymorph", expansion="mage turn target into sheep", zh="變羊術", cat="raid" },
    { term="sap", expansion="rogue Sap", zh="悶棍", cat="raid" },
    { term="trap", expansion="hunter trap", zh="陷阱", cat="raid" },
    { term="fear", expansion="warlock or priest fear", zh="恐懼", cat="raid" },
    { term="banish", expansion="warlock Banish", zh="放逐", cat="raid" },
    { term="shackle", expansion="priest Shackle Undead", zh="束縛亡靈", cat="raid" },
    { term="stun", expansion="stun effect", zh="暈眩", cat="combat" },
    { term="root", expansion="immobilize", zh="定身", cat="combat" },
    { term="snare", expansion="slow movement", zh="減速", cat="combat" },
    { term="slow", expansion="movement slow", zh="減速", cat="combat" },
    { term="silence", expansion="prevents spells", zh="沉默", cat="combat" },
    { term="interrupt", expansion="stop a spell cast", zh="打斷施法", cat="combat" },
    { term="kick", expansion="rogue Kick interrupt", zh="腳踢打斷", cat="combat" },
    { term="pummel", expansion="warrior interrupt", zh="拳擊打斷", cat="combat" },
    { term="dispel", expansion="remove magic effect", zh="驅散", cat="combat" },
    { term="decurse", expansion="remove curse", zh="解除詛咒", cat="combat" },
    { term="cleanse", expansion="remove disease or poison", zh="淨化", cat="combat" },
    { term="DoT", expansion="damage over time", zh="持續傷害", cat="combat" },
    { term="HoT", expansion="heal over time", zh="持續治療", cat="combat" },
    { term="AoE", expansion="area of effect", zh="範圍傷害", cat="combat" },
    { term="nuke", expansion="burst damage spell", zh="爆發傷害", cat="combat" },
    { term="burst", expansion="high short-term damage", zh="爆發", cat="combat" },
    { term="crit", expansion="critical hit", zh="暴擊", cat="combat" },
    { term="proc", expansion="random triggered effect", zh="觸發效果", cat="combat" },
    { term="CD", expansion="cooldown", zh="冷卻時間", cat="combat" },
    { term="cooldown", expansion="ability recharge time", zh="冷卻時間", cat="combat" },
    { term="GCD", expansion="global cooldown", zh="公共冷卻", cat="combat" },
    { term="DPS", expansion="damage per second or damage dealer", zh="輸出", cat="role" },
    { term="DD", expansion="damage dealer", zh="輸出", cat="role" },
    { term="HPS", expansion="healing per second", zh="每秒治療量", cat="combat" },
    { term="TPS", expansion="threat per second", zh="每秒仇恨", cat="combat" },
    { term="DPS meter", expansion="damage meter addon", zh="傷害統計插件", cat="combat" },
    { term="DBM", expansion="Deadly Boss Mods addon", zh="首領提示插件", cat="combat" },
    { term="BigWigs", expansion="boss timer addon", zh="首領計時插件", cat="combat" },
    { term="OOM", expansion="out of mana", zh="沒魔了", cat="combat" },
    { term="mana", expansion="spell resource", zh="魔力", cat="combat" },
    { term="drink", expansion="drink to regain mana", zh="喝水回魔", cat="combat" },
    { term="food", expansion="eat to regain health", zh="吃東西回血", cat="combat" },
    { term="eat", expansion="eat food to recover", zh="吃東西休息", cat="combat" },
    { term="rest", expansion="rest between pulls", zh="休息一下", cat="combat" },
    { term="regen", expansion="regenerate", zh="恢復", cat="combat" },
    { term="rage", expansion="warrior resource", zh="怒氣", cat="combat" },
    { term="energy", expansion="rogue resource", zh="能量", cat="combat" },
    { term="focus", expansion="focus fire on a target", zh="集火", cat="combat" },
    { term="focus fire", expansion="everyone attacks the same target", zh="集火", cat="combat" },
    { term="assist", expansion="target the tank's target", zh="協助攻擊", cat="combat" },
    { term="skull", expansion="skull raid marker (kill first)", zh="骷髏標記，先殺", cat="combat" },
    { term="X", expansion="X raid marker", zh="叉叉標記", cat="combat" },
    { term="moon", expansion="moon raid marker", zh="月亮標記", cat="combat" },
    { term="square", expansion="square raid marker", zh="方塊標記", cat="combat" },
    { term="triangle", expansion="triangle raid marker", zh="三角標記", cat="combat" },
    { term="diamond", expansion="diamond raid marker", zh="菱形標記", cat="combat" },
    { term="circle", expansion="circle raid marker", zh="圓圈標記", cat="combat" },
    { term="star", expansion="star raid marker", zh="星星標記", cat="combat" },
    { term="mark", expansion="raid target icon", zh="標記", cat="combat" },
    { term="nuke it", expansion="kill it with burst", zh="爆發秒掉", cat="combat" },
    { term="tank and spank", expansion="simple fight, tank holds, others dps", zh="單純坦怪輸出", cat="combat" },
    { term="stack", expansion="stand close together", zh="站一起", cat="combat" },
    { term="spread", expansion="spread out", zh="散開", cat="combat" },
    { term="move", expansion="move out of the area", zh="快移動", cat="combat" },
    { term="run away", expansion="flee", zh="快跑", cat="combat" },
    { term="stay", expansion="stay in place", zh="待在原地", cat="combat" },
    { term="wait", expansion="wait here", zh="等一下", cat="combat" },
    { term="hold", expansion="hold off attacking", zh="先別動手", cat="combat" },
    { term="stop", expansion="stop attacking", zh="停手", cat="combat" },
    { term="pat", expansion="patrol", zh="巡邏怪", cat="combat" },
    { term="patrol", expansion="roaming mob", zh="巡邏怪", cat="combat" },
    { term="evade", expansion="mob resets and heals", zh="怪脫戰回血", cat="combat" },
    { term="leash", expansion="mob returns to spawn", zh="怪被拉太遠會回去", cat="combat" },
    { term="DC", expansion="disconnected", zh="斷線", cat="combat" },
    { term="lag", expansion="network latency", zh="延遲卡頓", cat="combat" },
    { term="ping", expansion="latency", zh="延遲", cat="combat" },
    { term="dead", expansion="dead", zh="死了", cat="combat" },
    { term="died", expansion="died", zh="死了", cat="combat" },
    { term="release", expansion="release spirit", zh="放靈", cat="combat" },
    { term="repair", expansion="repair gear", zh="修裝", cat="combat" },
    { term="durability", expansion="gear condition", zh="耐久度", cat="combat" },
    { term="buff", expansion="beneficial effect", zh="增益", cat="combat" },
    { term="buffs", expansion="beneficial effects", zh="增益", cat="combat" },
    { term="debuff", expansion="harmful effect", zh="減益", cat="combat" },
    { term="world buffs", expansion="strong buffs from world bosses", zh="世界增益", cat="combat" },
    { term="flask", expansion="long-lasting raid potion", zh="精煉藥劑", cat="combat" },
    { term="elixir", expansion="stat potion", zh="藥劑", cat="combat" },
    { term="pot", expansion="potion", zh="藥水", cat="combat" },
    { term="potion", expansion="healing or mana potion", zh="藥水", cat="combat" },
    { term="consumes", expansion="consumables for raids", zh="消耗品", cat="combat" },
    { term="cons", expansion="consumables", zh="消耗品", cat="combat" },
    { term="healthstone", expansion="warlock heal item", zh="治療石", cat="combat" },
    { term="HS pot", expansion="healthstone and potion", zh="治療石加藥水", cat="combat" },
    { term="bandage", expansion="first aid bandage", zh="繃帶", cat="combat" },
    { term="first aid", expansion="bandage profession", zh="急救", cat="combat" },
    { term="CoR", expansion="Curse of Recklessness", zh="魯莽詛咒", cat="combat" },
    { term="CoE", expansion="Curse of the Elements", zh="元素詛咒", cat="combat" },
    { term="CoS", expansion="Curse of Shadow", zh="暗影詛咒", cat="combat" },
    { term="sunder", expansion="warrior armor debuff", zh="破甲", cat="combat" },
    { term="taunt", expansion="force mob to attack you", zh="嘲諷", cat="combat" },
    { term="shield wall", expansion="warrior defense cooldown", zh="盾牆", cat="combat" },
    { term="BoP buff", expansion="Blessing of Protection", zh="保護祝福", cat="combat" },
    { term="BoM", expansion="Blessing of Might", zh="力量祝福", cat="combat" },
    { term="BoW", expansion="Blessing of Wisdom", zh="智慧祝福", cat="combat" },
    { term="BoK", expansion="Blessing of Kings", zh="王者祝福", cat="combat" },
    { term="Fort", expansion="Power Word: Fortitude", zh="真言術：韌", cat="combat" },
    { term="MotW", expansion="Mark of the Wild", zh="野性印記", cat="combat" },
    { term="AI", expansion="Arcane Intellect", zh="奧術智慧", cat="combat" },
    { term="Innervate", expansion="druid mana restore spell", zh="啟動", cat="combat" },
    { term="Bloodlust", expansion="Horde shaman haste buff", zh="嗜血", cat="combat" },
    { term="Heroism", expansion="Alliance shaman haste buff", zh="英勇", cat="combat" },
    -- role
    { term="tank", expansion="damage-absorbing role", zh="坦克", cat="role" },
    { term="tnk", expansion="tank", zh="坦克", cat="role" },
    { term="heal", expansion="healing", zh="治療", cat="role" },
    { term="healer", expansion="healing role", zh="補師", cat="role" },
    { term="heals", expansion="healing", zh="補血", cat="role" },
    { term="tanks", expansion="tanks", zh="坦克們", cat="role" },
    { term="melee", expansion="close-range damage dealer", zh="近戰", cat="role" },
    { term="ranged", expansion="long-range damage dealer", zh="遠程", cat="role" },
    { term="caster", expansion="spell caster", zh="法系輸出", cat="role" },
    { term="range", expansion="ranged player", zh="遠程輸出", cat="role" },
    { term="hybrid", expansion="class that can fill multiple roles", zh="混合職業", cat="role" },
    { term="spec", expansion="talent specialization", zh="天賦專精", cat="role" },
    { term="respec", expansion="reset talents", zh="洗天賦", cat="role" },
    { term="talents", expansion="talent tree points", zh="天賦", cat="role" },
    { term="offspec", expansion="secondary spec", zh="副專精", cat="role" },
    { term="leader", expansion="group leader", zh="隊長", cat="role" },
    { term="RL", expansion="raid leader", zh="團長", cat="role" },
    { term="PL", expansion="party leader", zh="隊長", cat="role" },
    { term="GM", expansion="guild master or game master", zh="會長或遊戲管理員", cat="role" },
    { term="officer", expansion="guild officer", zh="幹部", cat="role" },
    { term="lead", expansion="lead the group", zh="帶隊", cat="role" },
    { term="healbot", expansion="player who heals all damage", zh="專職補師", cat="role" },
    { term="tank spec", expansion="tanking talent spec", zh="坦克天賦", cat="role" },
    { term="DPS warr", expansion="damage warrior", zh="輸出戰士", cat="role" },
    { term="prot", expansion="protection spec", zh="防護天賦", cat="role" },
    { term="resto", expansion="restoration spec", zh="恢復天賦", cat="role" },
    { term="holy", expansion="holy spec", zh="神聖天賦", cat="role" },
    { term="disc", expansion="discipline spec", zh="戒律天賦", cat="role" },
    { term="shadow", expansion="shadow priest spec", zh="暗影天賦", cat="role" },
    { term="ret", expansion="retribution paladin", zh="懲戒騎士", cat="role" },
    { term="boomkin", expansion="balance druid", zh="梟獸", cat="role" },
    { term="feral", expansion="feral druid", zh="野性德魯伊", cat="role" },
    { term="enh", expansion="enhancement shaman", zh="增強薩滿", cat="role" },
    { term="ele", expansion="elemental shaman", zh="元素薩滿", cat="role" },
    { term="fury", expansion="fury warrior", zh="狂怒戰士", cat="role" },
    { term="arms", expansion="arms warrior", zh="武器戰士", cat="role" },
    { term="BM", expansion="Beast Mastery", zh="野獸控制", cat="role" },
    { term="MM", expansion="Marksmanship", zh="射擊天賦", cat="role" },
    { term="SV", expansion="Survival", zh="生存天賦", cat="role" },
    { term="sub", expansion="subtlety rogue", zh="敏銳天賦", cat="role" },
    { term="combat", expansion="combat rogue", zh="戰鬥天賦", cat="role" },
    { term="aff lock", expansion="affliction warlock", zh="痛苦術士", cat="role" },
    { term="fire mage", expansion="fire spec mage", zh="火法", cat="role" },
    { term="frost mage", expansion="frost spec mage", zh="冰法", cat="role" },
    { term="arcane", expansion="arcane spec mage", zh="秘法", cat="role" },
    -- class
    { term="warr", expansion="Warrior", zh="戰士", cat="class" },
    { term="warrior", expansion="Warrior class", zh="戰士", cat="class" },
    { term="pally", expansion="Paladin", zh="聖騎士", cat="class" },
    { term="paladin", expansion="Paladin class", zh="聖騎士", cat="class" },
    { term="pal", expansion="Paladin", zh="聖騎士", cat="class" },
    { term="hunter", expansion="Hunter class", zh="獵人", cat="class" },
    { term="hunt", expansion="Hunter", zh="獵人", cat="class" },
    { term="rogue", expansion="Rogue class", zh="盜賊", cat="class" },
    { term="priest", expansion="Priest class", zh="牧師", cat="class" },
    { term="shammy", expansion="Shaman", zh="薩滿", cat="class" },
    { term="shaman", expansion="Shaman class", zh="薩滿", cat="class" },
    { term="sham", expansion="Shaman", zh="薩滿", cat="class" },
    { term="mage", expansion="Mage class", zh="法師", cat="class" },
    { term="lock", expansion="Warlock", zh="術士", cat="class" },
    { term="warlock", expansion="Warlock class", zh="術士", cat="class" },
    { term="druid", expansion="Druid class", zh="德魯伊", cat="class" },
    { term="pet", expansion="companion creature", zh="寵物", cat="class" },
    { term="imp", expansion="warlock imp pet", zh="小鬼", cat="class" },
    { term="voidwalker", expansion="warlock tank pet", zh="虛無行者", cat="class" },
    { term="VW", expansion="voidwalker", zh="虛無行者", cat="class" },
    { term="succubus", expansion="warlock pet", zh="魅魔", cat="class" },
    { term="felhunter", expansion="warlock anti-caster pet", zh="地獄獵犬", cat="class" },
    { term="totem", expansion="shaman totem", zh="圖騰", cat="class" },
    { term="aspect", expansion="hunter aspect", zh="守護", cat="class" },
    { term="stealth", expansion="rogue stealth", zh="潛行", cat="class" },
    { term="vanish", expansion="rogue escape skill", zh="消失", cat="class" },
    { term="sprint", expansion="rogue speed boost", zh="疾跑", cat="class" },
    { term="blink", expansion="mage short teleport", zh="閃現", cat="class" },
    { term="evocate", expansion="mage mana recovery", zh="喚醒", cat="class" },
    { term="water", expansion="mage conjured drink", zh="法師水", cat="class" },
    { term="conjure", expansion="create items", zh="製造", cat="class" },
    { term="feign", expansion="hunter feign death", zh="假死", cat="class" },
    { term="FD", expansion="Feign Death", zh="假死", cat="class" },
    { term="Misdirect", expansion="hunter threat transfer", zh="誤導", cat="class" },
    { term="shift", expansion="druid shapeshift", zh="變身", cat="class" },
    { term="bear", expansion="bear form druid tank", zh="熊形態", cat="class" },
    { term="cat", expansion="cat form druid", zh="貓形態", cat="class" },
    { term="HoJ", expansion="Hammer of Justice", zh="制裁之錘", cat="class" },
    { term="LoH", expansion="Lay on Hands", zh="聖療術", cat="class" },
    { term="DI", expansion="Divine Intervention", zh="神聖干涉", cat="class" },
    { term="Bubble", expansion="paladin Divine Shield", zh="無敵泡泡", cat="class" },
    { term="PI", expansion="Power Infusion", zh="能量灌注", cat="class" },
    { term="Fade", expansion="priest threat drop", zh="漸隱術", cat="class" },
    { term="Shield", expansion="Power Word: Shield", zh="真言術：盾", cat="class" },
    { term="rebuff", expansion="reapply buffs", zh="重新上增益", cat="class" },
    -- loot
    { term="loot", expansion="items dropped by enemies", zh="戰利品", cat="loot" },
    { term="drop", expansion="item dropped", zh="掉落", cat="loot" },
    { term="drops", expansion="items that drop", zh="掉落物", cat="loot" },
    { term="BoE", expansion="Bind on Equip", zh="裝備後綁定", cat="loot" },
    { term="BoP", expansion="Bind on Pickup", zh="拾取後綁定", cat="loot" },
    { term="BoU", expansion="Bind on Use", zh="使用後綁定", cat="loot" },
    { term="SR", expansion="Soft Reserve", zh="預訂裝備", cat="loot" },
    { term="HR", expansion="Hard Reserve", zh="指定裝備", cat="loot" },
    { term="MS", expansion="Main Spec", zh="主專精", cat="loot" },
    { term="OS", expansion="Off Spec", zh="副專精", cat="loot" },
    { term="MS>OS", expansion="main spec beats off spec", zh="主專精優先", cat="loot" },
    { term="greed", expansion="roll Greed", zh="貪婪", cat="loot" },
    { term="NBG", expansion="Need Before Greed", zh="需求優先", cat="loot" },
    { term="roll", expansion="random number roll", zh="骰點", cat="loot" },
    { term="/roll", expansion="roll command", zh="骰點指令", cat="loot" },
    { term="rolled", expansion="already rolled", zh="骰過了", cat="loot" },
    { term="pass", expansion="skip loot", zh="放棄", cat="loot" },
    { term="DE", expansion="disenchant", zh="分解", cat="loot" },
    { term="disenchant", expansion="break item into mats", zh="附魔分解", cat="loot" },
    { term="ninja", expansion="steal loot", zh="偷裝備", cat="loot" },
    { term="ninja'd", expansion="was stolen", zh="被偷拿了", cat="loot" },
    { term="ninjaed", expansion="stole loot", zh="偷拿裝備", cat="loot" },
    { term="master loot", expansion="leader distributes loot", zh="隊長分配", cat="loot" },
    { term="ML", expansion="master looter", zh="分配者", cat="loot" },
    { term="FFA", expansion="free for all", zh="自由拾取", cat="loot" },
    { term="RR", expansion="round robin loot", zh="輪流拾取", cat="loot" },
    { term="DKP", expansion="Dragon Kill Points", zh="DKP分數", cat="loot" },
    { term="GDKP", expansion="Gold DKP bidding", zh="金幣競標", cat="loot" },
    { term="bid", expansion="make an offer", zh="競標", cat="loot" },
    { term="epic", expansion="purple quality item", zh="紫裝", cat="loot" },
    { term="rare", expansion="blue quality item", zh="藍裝", cat="loot" },
    { term="green", expansion="green quality item", zh="綠裝", cat="loot" },
    { term="blue", expansion="blue quality item", zh="藍色裝備", cat="loot" },
    { term="purple", expansion="epic item", zh="紫色裝備", cat="loot" },
    { term="orange", expansion="legendary item", zh="傳說橘裝", cat="loot" },
    { term="legendary", expansion="orange quality item", zh="傳說", cat="loot" },
    { term="BiS", expansion="Best in Slot", zh="該部位最好", cat="loot" },
    { term="upgrade", expansion="better item", zh="升級裝備", cat="loot" },
    { term="gear", expansion="equipment", zh="裝備", cat="loot" },
    { term="geared", expansion="has good equipment", zh="裝備夠好", cat="loot" },
    { term="set", expansion="armor set", zh="套裝", cat="loot" },
    { term="tier", expansion="raid armor set tier", zh="套裝階級", cat="loot" },
    { term="T1", expansion="Tier 1 set", zh="第一套裝", cat="loot" },
    { term="T2", expansion="Tier 2 set", zh="第二套裝", cat="loot" },
    { term="token", expansion="set piece token", zh="套裝兌換物", cat="loot" },
    { term="trinket", expansion="trinket slot item", zh="飾品", cat="loot" },
    { term="BRE", expansion="Black Rock Enchanting items", zh="黑石附魔材料", cat="loot" },
    { term="rep", expansion="reputation", zh="聲望", cat="loot" },
    { term="exalted", expansion="highest reputation", zh="崇拜", cat="loot" },
    { term="revered", expansion="high reputation", zh="尊敬", cat="loot" },
    { term="attunement", expansion="raid entry quest chain", zh="進本任務", cat="loot" },
    { term="attune", expansion="complete attunement", zh="完成進本任務", cat="loot" },
    { term="key", expansion="dungeon key", zh="鑰匙", cat="loot" },
    { term="keys", expansion="dungeon keys", zh="鑰匙", cat="loot" },
    -- trade
    { term="WTS", expansion="Want To Sell", zh="出售", cat="trade" },
    { term="WTB", expansion="Want To Buy", zh="收購", cat="trade" },
    { term="WTT", expansion="Want To Trade", zh="想交換", cat="trade" },
    { term="LF craft", expansion="looking for crafter", zh="找人製作", cat="trade" },
    { term="CoD", expansion="Cash on Delivery", zh="貨到付款", cat="trade" },
    { term="mats", expansion="crafting materials", zh="材料", cat="trade" },
    { term="AH", expansion="Auction House", zh="拍賣場", cat="trade" },
    { term="auction", expansion="auction house listing", zh="拍賣", cat="trade" },
    { term="BO", expansion="buyout", zh="一口價", cat="trade" },
    { term="buyout", expansion="instant auction price", zh="一口價", cat="trade" },
    { term="g", expansion="gold", zh="金幣", cat="trade" },
    { term="gold", expansion="currency", zh="金幣", cat="trade" },
    { term="silver", expansion="currency", zh="銀幣", cat="trade" },
    { term="copper", expansion="currency", zh="銅幣", cat="trade" },
    { term="k", expansion="thousand", zh="千", cat="trade" },
    { term="obo", expansion="or best offer", zh="可議價", cat="trade" },
    { term="firm", expansion="price not negotiable", zh="不議價", cat="trade" },
    { term="tip", expansion="extra payment", zh="小費", cat="trade" },
    { term="free", expansion="no charge", zh="免費", cat="trade" },
    { term="tradeskill", expansion="crafting profession", zh="專業技能", cat="trade" },
    { term="prof", expansion="profession", zh="專業技能", cat="trade" },
    { term="profs", expansion="professions", zh="專業技能", cat="trade" },
    { term="alch", expansion="Alchemy", zh="鍊金術", cat="trade" },
    { term="BS", expansion="Blacksmithing", zh="鍛造", cat="trade" },
    { term="LW", expansion="Leatherworking", zh="製皮", cat="trade" },
    { term="tailor", expansion="Tailoring", zh="裁縫", cat="trade" },
    { term="enchant", expansion="Enchanting", zh="附魔", cat="trade" },
    { term="enchanter", expansion="player who enchants", zh="附魔師", cat="trade" },
    { term="engi", expansion="Engineering", zh="工程學", cat="trade" },
    { term="mining", expansion="gather ore", zh="採礦", cat="trade" },
    { term="herb", expansion="Herbalism", zh="草藥學", cat="trade" },
    { term="skinning", expansion="skin animals", zh="剝皮", cat="trade" },
    { term="fishing", expansion="Fishing", zh="釣魚", cat="trade" },
    { term="cooking", expansion="Cooking", zh="烹飪", cat="trade" },
    { term="ore", expansion="mining material", zh="礦石", cat="trade" },
    { term="bar", expansion="smelted metal bar", zh="金屬錠", cat="trade" },
    { term="leather", expansion="crafting material", zh="皮革", cat="trade" },
    { term="cloth", expansion="crafting material", zh="布料", cat="trade" },
    { term="runecloth", expansion="high-level cloth", zh="符文布", cat="trade" },
    { term="thorium", expansion="high-level ore", zh="瑟銀", cat="trade" },
    { term="arcanite", expansion="arcanite bar", zh="奧金", cat="trade" },
    { term="recipe", expansion="crafting recipe", zh="配方", cat="trade" },
    { term="pattern", expansion="crafting pattern", zh="圖樣", cat="trade" },
    { term="schematic", expansion="engineering recipe", zh="設計圖", cat="trade" },
    { term="formula", expansion="enchanting recipe", zh="公式", cat="trade" },
    { term="bag", expansion="container item", zh="背包", cat="trade" },
    { term="bags", expansion="inventory bags", zh="背包", cat="trade" },
    { term="mount", expansion="riding animal", zh="坐騎", cat="trade" },
    { term="epic mount", expansion="faster mount at level 60", zh="紫色坐騎", cat="trade" },
    { term="trade", expansion="open trade window", zh="交易", cat="trade" },
    { term="/trade", expansion="trade command", zh="交易指令", cat="trade" },
    { term="mail", expansion="in-game mail", zh="郵件", cat="trade" },
    { term="mailbox", expansion="mail box", zh="郵筒", cat="trade" },
    { term="vendor", expansion="NPC merchant", zh="商人", cat="trade" },
    { term="vendor trash", expansion="items to sell to NPC", zh="垃圾物品", cat="trade" },
    { term="bank", expansion="storage NPC", zh="銀行", cat="trade" },
    { term="guild bank", expansion="shared storage", zh="公會銀行", cat="trade" },
    { term="scam", expansion="fraud", zh="詐騙", cat="trade" },
    { term="scammer", expansion="fraud player", zh="詐騙者", cat="trade" },
    { term="gold seller", expansion="spam gold seller", zh="賣金幣廣告", cat="trade" },
    { term="boosting", expansion="paid carry", zh="付費代打", cat="trade" },
    -- social
    { term="ty", expansion="thank you", zh="謝謝", cat="social" },
    { term="thx", expansion="thanks", zh="謝了", cat="social" },
    { term="tyvm", expansion="thank you very much", zh="非常感謝", cat="social" },
    { term="np", expansion="no problem", zh="沒問題", cat="social" },
    { term="yw", expansion="you're welcome", zh="不客氣", cat="social" },
    { term="gg", expansion="good game", zh="打得好", cat="social" },
    { term="wp", expansion="well played", zh="打得漂亮", cat="social" },
    { term="gz", expansion="congratulations", zh="恭喜", cat="social" },
    { term="grats", expansion="congratulations", zh="恭喜", cat="social" },
    { term="gj", expansion="good job", zh="幹得好", cat="social" },
    { term="nice", expansion="good", zh="不錯", cat="social" },
    { term="nt", expansion="nice try", zh="可惜，不錯的嘗試", cat="social" },
    { term="nvm", expansion="never mind", zh="算了", cat="social" },
    { term="sry", expansion="sorry", zh="抱歉", cat="social" },
    { term="sorry", expansion="apology", zh="抱歉", cat="social" },
    { term="oops", expansion="my mistake", zh="糟糕", cat="social" },
    { term="my bad", expansion="my mistake", zh="我的錯", cat="social" },
    { term="mb", expansion="my bad", zh="我的錯", cat="social" },
    { term="pls", expansion="please", zh="拜託", cat="social" },
    { term="plz", expansion="please", zh="拜託", cat="social" },
    { term="afk", expansion="away from keyboard", zh="暫時離開", cat="social" },
    { term="brb", expansion="be right back", zh="馬上回來", cat="social" },
    { term="bbl", expansion="be back later", zh="晚點回來", cat="social" },
    { term="omw", expansion="on my way", zh="我在路上", cat="social" },
    { term="otw", expansion="on the way", zh="在路上", cat="social" },
    { term="eta", expansion="estimated time of arrival", zh="預計抵達時間", cat="social" },
    { term="b4", expansion="before", zh="之前", cat="social" },
    { term="gtg", expansion="got to go", zh="我得走了", cat="social" },
    { term="g2g", expansion="got to go", zh="我得走了", cat="social" },
    { term="cya", expansion="see you", zh="再見", cat="social" },
    { term="gn", expansion="good night", zh="晚安", cat="social" },
    { term="hi", expansion="hello", zh="嗨", cat="social" },
    { term="hey", expansion="hello", zh="嘿", cat="social" },
    { term="sup", expansion="what's up", zh="最近如何", cat="social" },
    { term="wb", expansion="welcome back", zh="歡迎回來", cat="social" },
    { term="lol", expansion="laughing out loud", zh="哈哈", cat="social" },
    { term="lmao", expansion="laughing my ass off", zh="笑死", cat="social" },
    { term="rofl", expansion="rolling on the floor laughing", zh="笑翻了", cat="social" },
    { term="haha", expansion="laughing", zh="哈哈", cat="social" },
    { term="kek", expansion="laugh (from Horde language)", zh="哈哈笑", cat="social" },
    { term="xD", expansion="laughing face", zh="大笑", cat="social" },
    { term="ofc", expansion="of course", zh="當然", cat="social" },
    { term="idk", expansion="I don't know", zh="我不知道", cat="social" },
    { term="idc", expansion="I don't care", zh="我不在乎", cat="social" },
    { term="imo", expansion="in my opinion", zh="我覺得", cat="social" },
    { term="imho", expansion="in my humble opinion", zh="依我淺見", cat="social" },
    { term="tbh", expansion="to be honest", zh="老實說", cat="social" },
    { term="btw", expansion="by the way", zh="順帶一提", cat="social" },
    { term="fyi", expansion="for your information", zh="供你參考", cat="social" },
    { term="irl", expansion="in real life", zh="現實生活中", cat="social" },
    { term="rn", expansion="right now", zh="現在", cat="social" },
    { term="atm", expansion="at the moment", zh="目前", cat="social" },
    { term="jk", expansion="just kidding", zh="開玩笑的", cat="social" },
    { term="omg", expansion="oh my god", zh="天啊", cat="social" },
    { term="wtf", expansion="what the f***", zh="搞什麼鬼", cat="social" },
    { term="smh", expansion="shaking my head", zh="無言", cat="social" },
    { term="ik", expansion="I know", zh="我知道", cat="social" },
    { term="u", expansion="you", zh="你", cat="social" },
    { term="ur", expansion="your or you're", zh="你的", cat="social" },
    { term="r", expansion="are", zh="是", cat="social" },
    { term="y", expansion="why", zh="為什麼", cat="social" },
    { term="ok", expansion="okay", zh="好", cat="social" },
    { term="kk", expansion="okay okay", zh="好的", cat="social" },
    { term="yep", expansion="yes", zh="對", cat="social" },
    { term="yea", expansion="yes", zh="對", cat="social" },
    { term="nah", expansion="no", zh="不", cat="social" },
    { term="nope", expansion="no", zh="不要", cat="social" },
    { term="sure", expansion="of course", zh="好啊", cat="social" },
    { term="sec", expansion="one second", zh="等我一下", cat="social" },
    { term="one sec", expansion="wait a moment", zh="等一下", cat="social" },
    { term="min", expansion="minute", zh="分鐘", cat="social" },
    { term="mins", expansion="minutes", zh="分鐘", cat="social" },
    { term="noob", expansion="newbie", zh="菜鳥", cat="social" },
    { term="n00b", expansion="newbie", zh="新手", cat="social" },
    { term="newb", expansion="newbie", zh="新手", cat="social" },
    { term="scrub", expansion="bad player", zh="弱雞", cat="social" },
    { term="trolling", expansion="provoking others", zh="亂入找碴", cat="social" },
    { term="troll", expansion="provocative player", zh="找碴的人", cat="social" },
    { term="kiddo", expansion="child player", zh="小朋友", cat="social" },
    { term="clown", expansion="foolish player", zh="小丑", cat="social" },
    { term="toxic", expansion="rude behavior", zh="言語惡劣", cat="social" },
    { term="rage quit", expansion="leave in anger", zh="氣到退出", cat="social" },
    { term="ragequit", expansion="leave in anger", zh="氣到退出", cat="social" },
    { term="vote kick", expansion="group votes to remove", zh="投票踢人", cat="social" },
    { term="ignore", expansion="block a player", zh="封鎖", cat="social" },
    { term="report", expansion="report a player", zh="檢舉", cat="social" },
    { term="guild", expansion="player organization", zh="公會", cat="social" },
    { term="gchat", expansion="guild chat", zh="公會頻道", cat="social" },
    { term="guildie", expansion="guild member", zh="公會成員", cat="social" },
    { term="guildies", expansion="guild members", zh="公會夥伴", cat="social" },
    { term="recruit", expansion="recruiting players", zh="招募", cat="social" },
    { term="recruiting", expansion="guild is recruiting", zh="公會招募中", cat="social" },
    { term="app", expansion="guild application", zh="入會申請", cat="social" },
    { term="friend", expansion="friend list entry", zh="好友", cat="social" },
    { term="add me", expansion="add me as a friend", zh="加我好友", cat="social" },
    { term="discord", expansion="voice chat app", zh="Discord語音", cat="social" },
    { term="vent", expansion="Ventrilo voice chat", zh="語音聊天", cat="social" },
    { term="TS", expansion="TeamSpeak", zh="TeamSpeak語音", cat="social" },
    { term="mic", expansion="microphone", zh="麥克風", cat="social" },
    { term="voice", expansion="voice chat", zh="語音", cat="social" },
    { term="addon", expansion="UI modification", zh="插件", cat="social" },
    { term="UI", expansion="user interface", zh="介面", cat="social" },
    { term="macro", expansion="scripted action", zh="巨集", cat="social" },
    { term="guide", expansion="walkthrough", zh="攻略", cat="social" },
    { term="tactic", expansion="boss strategy", zh="戰術", cat="social" },
    { term="explain", expansion="explain the fight", zh="說明打法", cat="social" },
    { term="first time", expansion="never done it before", zh="第一次打", cat="social" },
    { term="newbie", expansion="new player", zh="新手", cat="social" },
    { term="vet", expansion="veteran", zh="老手", cat="social" },
    { term="OG", expansion="original, veteran", zh="老玩家", cat="social" },
    { term="classic", expansion="original WoW", zh="經典版", cat="social" },
    { term="nostalgia", expansion="remembering the old days", zh="懷舊", cat="social" },
    { term="rip", expansion="rest in peace", zh="安息，慘了", cat="social" },
    { term="F", expansion="pay respects", zh="致哀", cat="social" },
    { term="pog", expansion="exciting moment", zh="太強了", cat="social" },
    { term="poggers", expansion="exciting moment", zh="太強了", cat="social" },
    { term="GOAT", expansion="greatest of all time", zh="史上最強", cat="social" },
    { term="insane", expansion="amazing", zh="太誇張", cat="social" },
    { term="sick", expansion="awesome", zh="超酷", cat="social" },
    { term="dope", expansion="cool", zh="很酷", cat="social" },
    { term="legit", expansion="genuine, real", zh="真的假的", cat="social" },
    { term="lit", expansion="exciting", zh="很嗨", cat="social" },
    { term="cringe", expansion="embarrassing", zh="很尷尬", cat="social" },
    { term="lame", expansion="uncool", zh="很遜", cat="social" },
    { term="sucks", expansion="is bad", zh="很爛", cat="social" },
    { term="sux", expansion="is bad", zh="很爛", cat="social" },
    { term="pwned", expansion="completely defeated", zh="被打爆", cat="social" },
    { term="owned", expansion="dominated", zh="被輾壓", cat="social" },
    { term="GL", expansion="good luck", zh="祝好運", cat="social" },
    { term="HF", expansion="have fun", zh="玩得開心", cat="social" },
    { term="glhf", expansion="good luck have fun", zh="祝好運玩得開心", cat="social" },
    { term="ggwp", expansion="good game well played", zh="打得好", cat="social" },
    { term="tysm", expansion="thank you so much", zh="非常謝謝", cat="social" },
    { term="pls inv", expansion="please invite", zh="拜託邀請我", cat="social" },
    { term="ez", expansion="easy", zh="很簡單", cat="social" },
    { term="rekt", expansion="destroyed", zh="被打爆", cat="social" },
    { term="wtfbbq", expansion="surprised exclamation", zh="天啊", cat="social" },
    { term="yolo", expansion="you only live once", zh="拚了", cat="social" },
    { term="hm", expansion="hmm", zh="嗯", cat="social" },
    { term="o7", expansion="salute", zh="敬禮", cat="social" },
    { term="<3", expansion="heart", zh="愛心", cat="social" },
    -- pvp / misc
    { term="PvP", expansion="player versus player", zh="玩家對戰", cat="misc" },
    { term="PvE", expansion="player versus environment", zh="打怪副本", cat="misc" },
    { term="BG", expansion="battleground", zh="戰場", cat="misc" },
    { term="WSG", expansion="Warsong Gulch", zh="戰歌峽谷", cat="misc" },
    { term="AB", expansion="Arathi Basin", zh="阿拉希盆地", cat="misc" },
    { term="AV", expansion="Alterac Valley", zh="奧特蘭克山谷", cat="misc" },
    { term="HK", expansion="honorable kill", zh="榮譽擊殺", cat="misc" },
    { term="honor", expansion="PvP currency", zh="榮譽", cat="misc" },
    { term="rank", expansion="PvP rank", zh="軍階", cat="misc" },
    { term="flag", expansion="battleground flag", zh="旗幟", cat="misc" },
    { term="FC", expansion="flag carrier", zh="旗手", cat="misc" },
    { term="EFC", expansion="enemy flag carrier", zh="敵方旗手", cat="misc" },
    { term="gank", expansion="surprise kill", zh="偷襲擊殺", cat="misc" },
    { term="ganked", expansion="was ambushed", zh="被偷襲", cat="misc" },
    { term="camp", expansion="wait at spawn or corpse", zh="蹲點守屍", cat="misc" },
    { term="camping", expansion="waiting for target", zh="蹲點中", cat="misc" },
    { term="corpse camp", expansion="kill players repeatedly", zh="守屍", cat="misc" },
    { term="PvP server", expansion="open-world PvP server", zh="PvP伺服器", cat="misc" },
    { term="flagged", expansion="PvP enabled", zh="開了PvP", cat="misc" },
    { term="duel", expansion="one-on-one fight", zh="決鬥", cat="misc" },
    { term="Horde", expansion="Horde faction", zh="部落", cat="misc" },
    { term="Alliance", expansion="Alliance faction", zh="聯盟", cat="misc" },
    { term="Ali", expansion="Alliance", zh="聯盟", cat="misc" },
    { term="all", expansion="everyone", zh="大家", cat="misc" },
    { term="realm", expansion="game server", zh="伺服器", cat="misc" },
    { term="server", expansion="game server", zh="伺服器", cat="misc" },
    { term="cross realm", expansion="players from other realms", zh="跨伺服器", cat="misc" },
    { term="channel", expansion="chat channel", zh="頻道", cat="misc" },
    { term="LFG channel", expansion="looking for group channel", zh="尋求組隊頻道", cat="misc" },
    { term="General", expansion="General chat channel", zh="綜合頻道", cat="misc" },
    { term="Trade chat", expansion="Trade channel", zh="交易頻道", cat="misc" },
    { term="local defense", expansion="LocalDefense channel", zh="本地防務頻道", cat="misc" },
    { term="spam", expansion="repeated messages", zh="洗頻", cat="misc" },
    { term="OT chat", expansion="off topic", zh="離題", cat="misc" },
    { term="TL;DR", expansion="too long; didn't read", zh="太長不看", cat="misc" },
    { term="RNG", expansion="random number generator, luck", zh="運氣", cat="misc" },
    { term="nerf", expansion="reduce power", zh="削弱", cat="misc" },
    { term="OP", expansion="overpowered", zh="太強", cat="misc" },
    { term="bug", expansion="game error", zh="程式錯誤", cat="misc" },
    { term="bugged", expansion="not working properly", zh="有問題", cat="misc" },
    { term="exploit", expansion="abuse a bug", zh="利用漏洞", cat="misc" },
    { term="hack", expansion="cheating program", zh="外掛", cat="misc" },
    { term="bot", expansion="automated player", zh="機器人", cat="misc" },
    { term="farm", expansion="repeat for resources", zh="刷素材", cat="misc" },
    { term="farming", expansion="repeat for resources", zh="刷東西中", cat="misc" },
    { term="spawn", expansion="monster appears", zh="怪物出現", cat="misc" },
    { term="respawn", expansion="monster reappears", zh="重新刷新", cat="misc" },
    { term="rare spawn", expansion="rare mob", zh="稀有怪", cat="misc" },
    { term="world boss", expansion="outdoor boss", zh="世界王", cat="misc" },
    { term="dragon", expansion="dragon", zh="龍", cat="misc" },
    { term="Azuregos", expansion="world boss in Azshara", zh="艾索雷苟斯", cat="misc" },
    { term="Kazzak", expansion="Lord Kazzak world boss", zh="卡札克", cat="misc" },
    { term="Dragons of Nightmare", expansion="four green dragons", zh="惡夢之龍", cat="misc" },
    { term="Ysondre", expansion="green dragon", zh="伊索德雷", cat="misc" },
    { term="DoN", expansion="Dragons of Nightmare", zh="惡夢之龍", cat="misc" },
    { term="Scarab", expansion="AQ scarab lord quest", zh="聖甲蟲", cat="misc" },
    { term="gate", expansion="AQ gong event", zh="開門事件", cat="misc" },
    { term="event", expansion="in-game event", zh="活動", cat="misc" },
    { term="Darkmoon", expansion="Darkmoon Faire", zh="暗月馬戲團", cat="misc" },
    { term="DMF", expansion="Darkmoon Faire", zh="暗月馬戲團", cat="misc" },
    { term="patch", expansion="game update", zh="改版", cat="misc" },
    { term="maint", expansion="server maintenance", zh="維修", cat="misc" },
    { term="downtime", expansion="server offline", zh="停機維護", cat="misc" },
    { term="queue", expansion="login queue", zh="排隊", cat="misc" },
    { term="login queue", expansion="waiting to enter server", zh="登入排隊", cat="misc" },
    { term="crash", expansion="game crash", zh="當機", cat="misc" },
    { term="relog", expansion="log out and in", zh="重新登入", cat="misc" },
    { term="log", expansion="log out", zh="登出", cat="misc" },
    { term="reload", expansion="reload UI", zh="重載介面", cat="misc" },
    { term="/reload", expansion="reload UI command", zh="重載介面指令", cat="misc" },
    { term="stuck", expansion="can't move", zh="卡住了", cat="misc" },
    { term="unstuck", expansion="free yourself", zh="脫離卡點", cat="misc" },
    { term="fall", expansion="fall damage", zh="摔落", cat="misc" },
    { term="jump", expansion="jump", zh="跳", cat="misc" },
    { term="skip", expansion="skip enemies", zh="跳過", cat="misc" },
    { term="skips", expansion="shortcuts past enemies", zh="跳過怪的路線", cat="misc" },
    { term="shortcut", expansion="quicker route", zh="捷徑", cat="misc" },
    { term="invis", expansion="invisibility potion", zh="隱形", cat="misc" },
    { term="mind control", expansion="priest MC", zh="精神控制", cat="misc" },
    { term="MC'd", expansion="mind controlled", zh="被精神控制", cat="misc" },
    { term="engineering", expansion="Engineering", zh="工程學", cat="misc" },
    { term="goggles", expansion="engineering goggles", zh="護目鏡", cat="misc" },
    { term="Arcanite Reaper", expansion="famed two-hand axe", zh="奧金斬斧", cat="misc" },
    { term="Thunderfury", expansion="legendary sword", zh="雷霆之怒", cat="misc" },
    { term="Sulfuras", expansion="legendary hammer", zh="薩弗拉斯", cat="misc" },
    { term="Onyxia cloak", expansion="Onyxia Scale Cloak", zh="奧妮克希亞披風", cat="misc" },
    { term="fire res", expansion="fire resistance", zh="火抗", cat="misc" },
    { term="FR", expansion="fire resistance", zh="火抗", cat="misc" },
    { term="NR", expansion="nature resistance", zh="自然抗性", cat="misc" },
    { term="SR gear", expansion="shadow resistance gear", zh="暗影抗性裝", cat="misc" },
    { term="res gear", expansion="resistance gear", zh="抗性裝", cat="misc" },
    { term="armor", expansion="damage mitigation stat", zh="護甲", cat="misc" },
    { term="stam", expansion="stamina", zh="耐力", cat="misc" },
    { term="int", expansion="intellect", zh="智力", cat="misc" },
    { term="str", expansion="strength", zh="力量", cat="misc" },
    { term="agi", expansion="agility", zh="敏捷", cat="misc" },
    { term="spirit", expansion="spirit stat", zh="精神", cat="misc" },
    { term="hit cap", expansion="maximum hit chance", zh="命中上限", cat="misc" },
    { term="hit", expansion="hit rating or chance", zh="命中", cat="misc" },
    { term="parry", expansion="avoid attack with weapon", zh="招架", cat="misc" },
    { term="dodge", expansion="avoid attack", zh="閃躲", cat="misc" },
    { term="block", expansion="shield block", zh="格擋", cat="misc" },
    { term="miss", expansion="attack misses", zh="未命中", cat="misc" },
    { term="resist", expansion="spell resisted", zh="被抵抗", cat="misc" },
    { term="immune", expansion="cannot be affected", zh="免疫", cat="misc" },
    { term="threat cap", expansion="threat limit", zh="仇恨上限", cat="misc" },
    { term="downrank", expansion="use lower spell rank", zh="使用低等級技能", cat="misc" },
    { term="max rank", expansion="highest spell rank", zh="最高等級技能", cat="misc" },
    { term="trainer", expansion="NPC that teaches skills", zh="訓練師", cat="misc" },
    { term="class quest", expansion="class-specific quest", zh="職業任務", cat="misc" },
    { term="mount quest", expansion="quest for mount", zh="坐騎任務", cat="misc" },
    { term="warlock mount", expansion="warlock epic mount quest", zh="術士坐騎", cat="misc" },
  },
  phrases = {
    ["ty"] = { zh="謝謝", terms={ {term="ty", expansion="thank you", zh="謝謝"} } },
    ["ty all"] = { zh="謝謝大家", terms={ {term="ty", expansion="thank you", zh="謝謝"} } },
    ["ty guys"] = { zh="謝謝各位", terms={ {term="ty", expansion="thank you", zh="謝謝"} } },
    ["ty for the run"] = { zh="謝謝帶我跑副本", terms={ {term="ty", expansion="thank you", zh="謝謝"} } },
    ["ty for the invite"] = { zh="謝謝邀請", terms={ {term="ty", expansion="thank you", zh="謝謝"} } },
    ["ty for the inv"] = { zh="謝謝邀請", terms={ {term="ty", expansion="thank you", zh="謝謝"}, {term="inv", expansion="invite", zh="邀請"} } },
    ["ty for the heal"] = { zh="謝謝補血", terms={ {term="ty", expansion="thank you", zh="謝謝"} } },
    ["ty for the buff"] = { zh="謝謝增益", terms={ {term="ty", expansion="thank you", zh="謝謝"} } },
    ["ty for the port"] = { zh="謝謝傳送", terms={ {term="ty", expansion="thank you", zh="謝謝"}, {term="port", expansion="teleport", zh="傳送"} } },
    ["ty for the summon"] = { zh="謝謝召喚", terms={ {term="ty", expansion="thank you", zh="謝謝"} } },
    ["ty for the rez"] = { zh="謝謝復活", terms={ {term="ty", expansion="thank you", zh="謝謝"}, {term="rez", expansion="resurrect", zh="復活"} } },
    ["thx"] = { zh="謝了", terms={ {term="thx", expansion="thanks", zh="謝了"} } },
    ["thx all"] = { zh="謝謝大家", terms={ {term="thx", expansion="thanks", zh="謝了"} } },
    ["thanks"] = { zh="謝謝", terms={} },
    ["thanks all"] = { zh="謝謝大家", terms={} },
    ["thank you"] = { zh="謝謝你", terms={} },
    ["tyvm"] = { zh="非常感謝", terms={ {term="tyvm", expansion="thank you very much", zh="非常感謝"} } },
    ["np"] = { zh="沒問題", terms={ {term="np", expansion="no problem", zh="沒問題"} } },
    ["np at all"] = { zh="完全沒問題", terms={ {term="np", expansion="no problem", zh="沒問題"} } },
    ["no problem"] = { zh="沒問題", terms={} },
    ["yw"] = { zh="不客氣", terms={ {term="yw", expansion="you're welcome", zh="不客氣"} } },
    ["gg"] = { zh="打得好", terms={ {term="gg", expansion="good game", zh="打得好"} } },
    ["gg all"] = { zh="大家打得好", terms={ {term="gg", expansion="good game", zh="打得好"} } },
    ["gg wp"] = { zh="打得漂亮", terms={ {term="gg", expansion="good game", zh="打得好"}, {term="wp", expansion="well played", zh="打得漂亮"} } },
    ["ggwp"] = { zh="打得漂亮", terms={ {term="ggwp", expansion="good game well played", zh="打得好"} } },
    ["wp"] = { zh="打得漂亮", terms={ {term="wp", expansion="well played", zh="打得漂亮"} } },
    ["gj"] = { zh="幹得好", terms={ {term="gj", expansion="good job", zh="幹得好"} } },
    ["gj all"] = { zh="大家幹得好", terms={ {term="gj", expansion="good job", zh="幹得好"} } },
    ["good job"] = { zh="幹得好", terms={} },
    ["nice"] = { zh="不錯", terms={} },
    ["nice one"] = { zh="漂亮", terms={} },
    ["nt"] = { zh="可惜，不錯的嘗試", terms={ {term="nt", expansion="nice try", zh="不錯的嘗試"} } },
    ["gz"] = { zh="恭喜", terms={ {term="gz", expansion="congratulations", zh="恭喜"} } },
    ["grats"] = { zh="恭喜", terms={ {term="grats", expansion="congratulations", zh="恭喜"} } },
    ["congrats"] = { zh="恭喜", terms={} },
    ["omw"] = { zh="我在路上", terms={ {term="omw", expansion="on my way", zh="我在路上"} } },
    ["omw now"] = { zh="我現在就過去", terms={ {term="omw", expansion="on my way", zh="我在路上"} } },
    ["otw"] = { zh="在路上", terms={ {term="otw", expansion="on the way", zh="在路上"} } },
    ["on my way"] = { zh="我在路上", terms={} },
    ["be right there"] = { zh="馬上到", terms={} },
    ["brb"] = { zh="馬上回來", terms={ {term="brb", expansion="be right back", zh="馬上回來"} } },
    ["bbl"] = { zh="晚點回來", terms={ {term="bbl", expansion="be back later", zh="晚點回來"} } },
    ["back"] = { zh="我回來了", terms={} },
    ["wb"] = { zh="歡迎回來", terms={ {term="wb", expansion="welcome back", zh="歡迎回來"} } },
    ["afk"] = { zh="暫時離開", terms={ {term="afk", expansion="away from keyboard", zh="暫時離開"} } },
    ["afk 1 min"] = { zh="離開一分鐘", terms={ {term="afk", expansion="away from keyboard", zh="暫時離開"} } },
    ["afk 5 min"] = { zh="離開五分鐘", terms={ {term="afk", expansion="away from keyboard", zh="暫時離開"} } },
    ["one sec"] = { zh="等一下", terms={} },
    ["sec"] = { zh="等我一下", terms={ {term="sec", expansion="one second", zh="等我一下"} } },
    ["wait"] = { zh="等一下", terms={} },
    ["hold on"] = { zh="等一下", terms={} },
    ["inv"] = { zh="邀請", terms={ {term="inv", expansion="invite", zh="邀請"} } },
    ["inv pls"] = { zh="請邀請我", terms={ {term="inv", expansion="invite", zh="邀請"}, {term="pls", expansion="please", zh="拜託"} } },
    ["pls inv"] = { zh="請邀請我", terms={ {term="inv", expansion="invite", zh="邀請"}, {term="pls", expansion="please", zh="拜託"} } },
    ["inv please"] = { zh="請邀請我", terms={ {term="inv", expansion="invite", zh="邀請"} } },
    ["invite"] = { zh="邀請我", terms={} },
    ["invite pls"] = { zh="請邀請我", terms={ {term="pls", expansion="please", zh="拜託"} } },
    ["inv me"] = { zh="邀請我", terms={ {term="inv", expansion="invite", zh="邀請"} } },
    ["inv plz"] = { zh="請邀請我", terms={ {term="inv", expansion="invite", zh="邀請"}, {term="plz", expansion="please", zh="拜託"} } },
    ["summon pls"] = { zh="請召喚我", terms={ {term="pls", expansion="please", zh="拜託"} } },
    ["sum pls"] = { zh="請召喚我", terms={ {term="pls", expansion="please", zh="拜託"} } },
    ["summ pls"] = { zh="請召喚我", terms={ {term="summ", expansion="summon", zh="召喚"}, {term="pls", expansion="please", zh="拜託"} } },
    ["port pls"] = { zh="請傳送我", terms={ {term="port", expansion="teleport", zh="傳送"}, {term="pls", expansion="please", zh="拜託"} } },
    ["lf tank"] = { zh="找坦克", terms={ {term="lf", expansion="looking for", zh="尋找"}, {term="tank", expansion="tank", zh="坦克"} } },
    ["lf healer"] = { zh="找補師", terms={ {term="lf", expansion="looking for", zh="尋找"}, {term="healer", expansion="healer", zh="補師"} } },
    ["lf heals"] = { zh="找補師", terms={ {term="lf", expansion="looking for", zh="尋找"}, {term="heals", expansion="healer", zh="補師"} } },
    ["lf dps"] = { zh="找輸出", terms={ {term="lf", expansion="looking for", zh="尋找"}, {term="dps", expansion="damage dealer", zh="輸出"} } },
    ["lfg"] = { zh="找隊伍", terms={ {term="lfg", expansion="looking for group", zh="找隊伍"} } },
    ["lfm"] = { zh="徵人", terms={ {term="lfm", expansion="looking for more", zh="徵人"} } },
    ["lf1m"] = { zh="還缺一人", terms={ {term="lf1m", expansion="looking for 1 more", zh="還缺一人"} } },
    ["lf2m"] = { zh="還缺兩人", terms={ {term="lf2m", expansion="looking for 2 more", zh="還缺兩人"} } },
    ["need tank"] = { zh="缺坦克", terms={ {term="tank", expansion="tank", zh="坦克"} } },
    ["need heals"] = { zh="缺補師", terms={ {term="heals", expansion="healing", zh="補血"} } },
    ["need healer"] = { zh="缺補師", terms={ {term="healer", expansion="healer", zh="補師"} } },
    ["need dps"] = { zh="缺輸出", terms={ {term="dps", expansion="damage dealer", zh="輸出"} } },
    ["ready"] = { zh="準備好了", terms={} },
    ["ready?"] = { zh="準備好了嗎", terms={} },
    ["rdy"] = { zh="準備好了", terms={ {term="rdy", expansion="ready", zh="準備好了"} } },
    ["rdy?"] = { zh="準備好了嗎", terms={ {term="rdy", expansion="ready", zh="準備好了"} } },
    ["all ready"] = { zh="大家都準備好了", terms={} },
    ["not ready"] = { zh="還沒好", terms={} },
    ["not yet"] = { zh="還沒", terms={} },
    ["go"] = { zh="開始", terms={} },
    ["go go go"] = { zh="衝衝衝", terms={} },
    ["lets go"] = { zh="走吧", terms={} },
    ["pull"] = { zh="拉怪", terms={ {term="pull", expansion="start fight with a mob", zh="拉怪"} } },
    ["pulling"] = { zh="我來拉怪了", terms={ {term="pulling", expansion="pulling mobs", zh="正在拉怪"} } },
    ["wipe"] = { zh="滅團了", terms={ {term="wipe", expansion="whole group dies", zh="滅團"} } },
    ["rez pls"] = { zh="請復活我", terms={ {term="rez", expansion="resurrect", zh="復活"}, {term="pls", expansion="please", zh="拜託"} } },
    ["rez"] = { zh="請復活", terms={ {term="rez", expansion="resurrect", zh="復活"} } },
    ["oom"] = { zh="沒魔了", terms={ {term="oom", expansion="out of mana", zh="沒魔了"} } },
    ["drink"] = { zh="喝水回魔", terms={ {term="drink", expansion="drink to regain mana", zh="喝水回魔"} } },
    ["need drink"] = { zh="需要喝水", terms={} },
    ["need to drink"] = { zh="得喝水", terms={} },
    ["sorry"] = { zh="抱歉", terms={} },
    ["sry"] = { zh="抱歉", terms={ {term="sry", expansion="sorry", zh="抱歉"} } },
    ["my bad"] = { zh="我的錯", terms={} },
    ["mb"] = { zh="我的錯", terms={ {term="mb", expansion="my bad", zh="我的錯"} } },
    ["oops"] = { zh="糟糕", terms={} },
    ["lol"] = { zh="哈哈", terms={ {term="lol", expansion="laughing out loud", zh="哈哈"} } },
    ["lmao"] = { zh="笑死", terms={ {term="lmao", expansion="laughing my ass off", zh="笑死"} } },
    ["kek"] = { zh="哈哈笑", terms={ {term="kek", expansion="laugh", zh="哈哈笑"} } },
    ["haha"] = { zh="哈哈", terms={} },
    ["ofc"] = { zh="當然", terms={ {term="ofc", expansion="of course", zh="當然"} } },
    ["of course"] = { zh="當然", terms={} },
    ["idk"] = { zh="我不知道", terms={ {term="idk", expansion="I don't know", zh="我不知道"} } },
    ["i dont know"] = { zh="我不知道", terms={} },
    ["nvm"] = { zh="算了", terms={ {term="nvm", expansion="never mind", zh="算了"} } },
    ["never mind"] = { zh="算了", terms={} },
    ["ok"] = { zh="好", terms={} },
    ["okay"] = { zh="好", terms={} },
    ["k"] = { zh="好", terms={ {term="k", expansion="okay", zh="好"} } },
    ["kk"] = { zh="好的", terms={ {term="kk", expansion="okay okay", zh="好的"} } },
    ["yes"] = { zh="是", terms={} },
    ["yep"] = { zh="對", terms={ {term="yep", expansion="yes", zh="對"} } },
    ["yeah"] = { zh="對", terms={} },
    ["no"] = { zh="不", terms={} },
    ["nope"] = { zh="不要", terms={ {term="nope", expansion="no", zh="不要"} } },
    ["sure"] = { zh="好啊", terms={} },
    ["pls"] = { zh="拜託", terms={ {term="pls", expansion="please", zh="拜託"} } },
    ["please"] = { zh="拜託", terms={} },
    ["hi"] = { zh="嗨", terms={} },
    ["hello"] = { zh="哈囉", terms={} },
    ["hey"] = { zh="嘿", terms={} },
    ["hi all"] = { zh="大家好", terms={} },
    ["hi guys"] = { zh="各位好", terms={} },
    ["sup"] = { zh="最近如何", terms={ {term="sup", expansion="what's up", zh="最近如何"} } },
    ["bye"] = { zh="再見", terms={} },
    ["bb"] = { zh="掰掰", terms={ {term="bb", expansion="bye bye", zh="掰掰"} } },
    ["cya"] = { zh="再見", terms={ {term="cya", expansion="see you", zh="再見"} } },
    ["gtg"] = { zh="我得走了", terms={ {term="gtg", expansion="got to go", zh="我得走了"} } },
    ["g2g"] = { zh="我得走了", terms={ {term="g2g", expansion="got to go", zh="我得走了"} } },
    ["gn"] = { zh="晚安", terms={ {term="gn", expansion="good night", zh="晚安"} } },
    ["good night"] = { zh="晚安", terms={} },
    ["gm"] = { zh="早安", terms={ {term="gm", expansion="good morning", zh="早安"} } },
    ["good morning"] = { zh="早安", terms={} },
    ["glhf"] = { zh="祝好運玩得開心", terms={ {term="glhf", expansion="good luck have fun", zh="祝好運玩得開心"} } },
    ["gl"] = { zh="祝好運", terms={ {term="gl", expansion="good luck", zh="祝好運"} } },
    ["good luck"] = { zh="祝好運", terms={} },
    ["hf"] = { zh="玩得開心", terms={ {term="hf", expansion="have fun", zh="玩得開心"} } },
    ["ez"] = { zh="很簡單", terms={ {term="ez", expansion="easy", zh="很簡單"} } },
    ["rip"] = { zh="安息，慘了", terms={ {term="rip", expansion="rest in peace", zh="慘了"} } },
    ["f"] = { zh="致哀", terms={ {term="f", expansion="pay respects", zh="致哀"} } },
    ["omg"] = { zh="天啊", terms={ {term="omg", expansion="oh my god", zh="天啊"} } },
    ["wtf"] = { zh="搞什麼鬼", terms={ {term="wtf", expansion="what the f***", zh="搞什麼鬼"} } },
    ["jk"] = { zh="開玩笑的", terms={ {term="jk", expansion="just kidding", zh="開玩笑的"} } },
    ["imo"] = { zh="我覺得", terms={ {term="imo", expansion="in my opinion", zh="我覺得"} } },
    ["lvl 60"] = { zh="六十級", terms={ {term="lvl", expansion="level", zh="等級"} } },
    ["need a summon"] = { zh="需要召喚", terms={} },
    ["can i get an inv"] = { zh="可以邀請我嗎", terms={ {term="inv", expansion="invite", zh="邀請"} } },
    ["can i get inv"] = { zh="可以邀請我嗎", terms={ {term="inv", expansion="invite", zh="邀請"} } },
    ["can i get a summon"] = { zh="可以召喚我嗎", terms={} },
    ["can i get a port"] = { zh="可以傳送我嗎", terms={ {term="port", expansion="teleport", zh="傳送"} } },
    ["can i join"] = { zh="我可以加入嗎", terms={} },
    ["still need"] = { zh="還缺人嗎", terms={} },
    ["still lf"] = { zh="還在找嗎", terms={ {term="lf", expansion="looking for", zh="尋找"} } },
    ["still looking"] = { zh="還在找人", terms={} },
    ["group full"] = { zh="隊伍滿了", terms={} },
    ["full"] = { zh="滿了", terms={ {term="full", expansion="group is full", zh="滿了"} } },
    ["thanks for the invite"] = { zh="謝謝邀請", terms={} },
    ["thanks for the run"] = { zh="謝謝帶我跑", terms={} },
    ["thanks for the heal"] = { zh="謝謝補血", terms={} },
    ["thanks for the buff"] = { zh="謝謝增益", terms={} },
    ["where are you"] = { zh="你在哪裡", terms={} },
    ["where"] = { zh="在哪", terms={} },
    ["meet at stone"] = { zh="在集合石集合", terms={ {term="stone", expansion="meeting stone", zh="集合石"} } },
    ["at the stone"] = { zh="在集合石這邊", terms={ {term="stone", expansion="meeting stone", zh="集合石"} } },
    ["at stone"] = { zh="在集合石這邊", terms={ {term="stone", expansion="meeting stone", zh="集合石"} } },
    ["sum"] = { zh="召喚", terms={ {term="summ", expansion="summon", zh="召喚"} } },
    ["need rez"] = { zh="需要復活", terms={ {term="rez", expansion="resurrect", zh="復活"} } },
    ["release"] = { zh="放靈", terms={ {term="release", expansion="release spirit", zh="放靈"} } },
    ["dc"] = { zh="斷線了", terms={ {term="dc", expansion="disconnected", zh="斷線"} } },
    ["lag"] = { zh="我卡了", terms={ {term="lag", expansion="network latency", zh="延遲卡頓"} } },
    ["lagging"] = { zh="我很卡", terms={} },
    ["dced"] = { zh="我斷線了", terms={ {term="dc", expansion="disconnected", zh="斷線"} } },
    ["relog"] = { zh="重新登入", terms={ {term="relog", expansion="log out and in", zh="重新登入"} } },
    ["need roll"] = { zh="要骰需求", terms={ {term="roll", expansion="random number roll", zh="骰點"} } },
    ["pass"] = { zh="放棄", terms={ {term="pass", expansion="skip loot", zh="放棄"} } },
    ["greed"] = { zh="貪婪", terms={ {term="greed", expansion="roll Greed", zh="貪婪"} } },
    ["need"] = { zh="需求", terms={ {term="need", expansion="roll Need", zh="需求"} } },
    ["rolling"] = { zh="我來骰", terms={} },
    ["main spec"] = { zh="主專精", terms={} },
    ["ms"] = { zh="主專精", terms={ {term="ms", expansion="main spec", zh="主專精"} } },
    ["os"] = { zh="副專精", terms={ {term="os", expansion="off spec", zh="副專精"} } },
    ["boe"] = { zh="裝備後綁定", terms={ {term="boe", expansion="bind on equip", zh="裝備後綁定"} } },
    ["bop"] = { zh="拾取後綁定", terms={ {term="bop", expansion="bind on pickup", zh="拾取後綁定"} } },
    ["wts"] = { zh="出售", terms={ {term="wts", expansion="want to sell", zh="出售"} } },
    ["wtb"] = { zh="收購", terms={ {term="wtb", expansion="want to buy", zh="收購"} } },
    ["wtt"] = { zh="想交換", terms={ {term="wtt", expansion="want to trade", zh="想交換"} } },
    ["pst"] = { zh="請密我", terms={ {term="pst", expansion="please send tell", zh="請密我"} } },
    ["pm me"] = { zh="私訊我", terms={ {term="pm", expansion="private message", zh="私訊"} } },
    ["add me"] = { zh="加我好友", terms={} },
    ["trade me"] = { zh="跟我交易", terms={} },
    ["free"] = { zh="免費", terms={} },
    ["free port"] = { zh="免費傳送", terms={ {term="port", expansion="teleport", zh="傳送"} } },
    ["stop"] = { zh="停手", terms={} },
    ["stop pulling"] = { zh="別再拉怪", terms={} },
    ["dont pull"] = { zh="先別拉怪", terms={} },
    ["wait for mana"] = { zh="等魔力恢復", terms={} },
    ["wait for heals"] = { zh="等補師", terms={} },
    ["need mana"] = { zh="需要補魔", terms={} },
    ["need food"] = { zh="需要吃東西", terms={} },
    ["one more"] = { zh="再一個", terms={} },
    ["last pull"] = { zh="最後一波", terms={} },
    ["last boss"] = { zh="最後一隻王", terms={} },
    ["next boss"] = { zh="下一隻王", terms={} },
    ["well done"] = { zh="做得好", terms={} },
    ["welcome"] = { zh="歡迎", terms={} },
    ["no worries"] = { zh="別擔心", terms={} },
    ["its ok"] = { zh="沒關係", terms={} },
    ["all good"] = { zh="沒事", terms={} },
    ["same"] = { zh="我也是", terms={} },
    ["me too"] = { zh="我也是", terms={} },
    ["true"] = { zh="沒錯", terms={} },
    ["facts"] = { zh="說得對", terms={} },
    ["lets do it"] = { zh="就這麼辦", terms={} },
  },
}
